name: 'publish'

on:
  push:
    branches:
      - deploy

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            args: '--target node16-macos-arm64'
          - platform: 'macos-latest' # for Intel based macs.
            args: '--target node16-macos-x64'
          - platform: 'windows-latest' # for Windows.
            args: '--target node16-win-x64'

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
  
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable corepack
        run: corepack enable

      - name: install frontend dependencies
        run: pnpm install

      - name: Get version from package.json
        id: get_version
        run: echo "VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV

      - name: Package with pkg
        run: pnpx pkg . --public ${{ matrix.args }} --output dist/seajob-executor-${{ matrix.platform }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: 'v0.0.1' # 使用 package.json 中的版本号
          release_name: 'seajob-executor Release v0.0.1'
          draft: true
          prerelease: false
      
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/seajob-executor-${{ matrix.platform }}
          asset_name: seajob-executor-${{ matrix.platform }}-${{ matrix.args }}
          asset_content_type: application/octet-stream