name: 'publish'

on:
  push:
    branches:
      - deploy

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target node16-macos-arm64'
            file_suffix: 'macos-arm64'
          - platform: 'macos-latest'
            args: '--target node16-macos-x64'
            file_suffix: 'macos-x64'
          - platform: 'windows-latest'
            args: '--target node16-win-x64'
            file_suffix: 'windows-x64.exe'

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
  
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable corepack
        run: corepack enable

      - name: install frontend dependencies
        run: pnpm install

      - name: Get version from package.json
        id: get_version
        run: echo "VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV

      - name: Package with pkg
        run: pnpx pkg . --public ${{ matrix.args }} --output dist/seajob-executor-${{ matrix.file_suffix }}
      
      - name: List dist directory (debug)
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            dir dist
          else
            ls -la dist
          fi
        shell: bash

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/seajob-executor-${{ matrix.file_suffix }}
          draft: false
          prerelease: false
          make_latest: true
