name: 'publish'

on:
  push:
    branches:
      - deploy

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            args: '--target node16-macos-arm64'
          - platform: 'macos-latest' # for Intel based macs.
            args: '--target node16-macos-x64'
          - platform: 'windows-latest' # for Windows.
            args: '--target node16-win-x64'

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
  
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable corepack
        run: corepack enable

      - name: install frontend dependencies
        run: pnpm install

      - name: Package with pkg
        run: pnpx pkg . --public ${{ matrix.args }} --output dist/seajob-executor-${{ matrix.platform }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: seajob-executor-${{ matrix.platform }}
          path: dist/seajob-executor-${{ matrix.platform }}